### ISSUE TITLE
Crashes if the user has no ISOs

### ISSUE THREAD

**Issue by znew711** [harrison-caudill/ipo-sim#5]
```
Traceback (most recent call last):
  File "investigator.py", line 228, in <module>
    dixon_hill.go()
  File "investigator.py", line 220, in go
    self.question_6()
  File "investigator.py", line 142, in question_6
    (amt, n, strike, cost) = self.amt_free_iso()
  File "investigator.py", line 111, in amt_free_iso
    g = [g for g in m.grants_lst if g.vehicle=='iso'][0]
```

**Comment by harrison-caudill** [comment]
ah yes.  It's one of the examples, so no big deal if it is skipped, but probably not the best user experience.

will-fix -- working on something else for a few hours.

**Comment by harrison-caudill** [comment]
try now that #8 has been merged.

**Comment by harrison-caudill** [comment]
@znew711 Should this issue be closed?

**Comment by znew711** [comment]
Your logic looks good, I will close!
i won't have time to test until later tonight
